/-
Copyright (c) 2026 QuAIR.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QuAIR Team
-/

module

public import QIT.Protocols.FQSW.Core
public import Mathlib.Analysis.Fourier.ZMod
public import Mathlib.LinearAlgebra.Matrix.Permutation
public import Mathlib.LinearAlgebra.UnitaryGroup

/-!
# Exact finite-dimensional qudit teleportation

This module follows Wilde's qudit teleportation calculation: Alice measures in
the generalized Bell basis generated by finite Weyl shift/phase operators,
communicates the two finite outcomes, and Bob applies the outcome-dependent
Weyl correction.  Contracting the Bell vector with the shared maximally
entangled vector gives the uncorrected Kraus operator; the correction reduces
every branch to a scalar multiple of the identity.  Summing the corrected
branches therefore gives the identity channel, including in the presence of
an arbitrary inaccessible reference system.

Source: [Wilde2011Qst, qit-notes.tex:12506-12694].
-/

@[expose] public section

open scoped ComplexOrder MatrixOrder

namespace QIT

universe u v

noncomputable section

private theorem fintype_card_pos
    (d : Type u) [Fintype d] [Nonempty d] : 0 < Fintype.card d :=
  Fintype.card_pos_iff.mpr inferInstance

private noncomputable instance card_neZero
    (d : Type u) [Fintype d] [Nonempty d] : NeZero (Fintype.card d) :=
  ⟨Nat.ne_of_gt (fintype_card_pos d)⟩

/-- Canonical cyclic labeling of an arbitrary finite nonempty register. -/
def cyclicBasisEquiv (d : Type u) [Fintype d] [Nonempty d] :
    d ≃ ZMod (Fintype.card d) :=
  (Fintype.equivFin d).trans (ZMod.finEquiv (Fintype.card d)).toEquiv

/-- The cyclic shift permutation `|x> ↦ |x+i>` in the canonical cyclic basis. -/
def teleportationShiftPerm
    (d : Type u) [Fintype d] [Nonempty d] (i : d) : Equiv.Perm d where
  toFun x := (cyclicBasisEquiv d).symm (cyclicBasisEquiv d x + cyclicBasisEquiv d i)
  invFun x := (cyclicBasisEquiv d).symm (cyclicBasisEquiv d x - cyclicBasisEquiv d i)
  left_inv x := by
    apply (cyclicBasisEquiv d).injective
    simp
  right_inv x := by
    apply (cyclicBasisEquiv d).injective
    simp

/-- Matrix of the cyclic shift `X(i)`. -/
def teleportationShift
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] (i : d) : CMatrix d :=
  ((teleportationShiftPerm d i)⁻¹).permMatrix ℂ

/-- Diagonal phase matrix `Z(j)` in the canonical cyclic basis. -/
def teleportationPhase
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] (j : d) : CMatrix d :=
  Matrix.diagonal fun x =>
    ZMod.stdAddChar (cyclicBasisEquiv d j * cyclicBasisEquiv d x)

/-- Finite Weyl operator `U^(i,j) = Z(j) X(i)`. -/
def teleportationWeyl
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) : CMatrix d :=
  teleportationPhase d outcome.2 * teleportationShift d outcome.1

private theorem star_stdAddChar_mul_self
    {n : ℕ} [NeZero n] (x : ZMod n) :
    star (ZMod.stdAddChar x) * ZMod.stdAddChar x = 1 := by
  rw [ZMod.stdAddChar_apply, Complex.star_def, ← Circle.coe_inv_eq_conj]
  rw [← Circle.coe_mul]
  simp

private theorem stdAddChar_mul_star_self
    {n : ℕ} [NeZero n] (x : ZMod n) :
    ZMod.stdAddChar x * star (ZMod.stdAddChar x) = 1 := by
  simpa [mul_comm] using star_stdAddChar_mul_self x

private theorem star_stdAddChar_eq_neg
    {n : ℕ} [NeZero n] (x : ZMod n) :
    star (ZMod.stdAddChar x) = ZMod.stdAddChar (-x) := by
  rw [ZMod.stdAddChar_apply, ZMod.stdAddChar_apply, Complex.star_def,
    ← Circle.coe_inv_eq_conj]
  exact congrArg ((↑) : Circle → ℂ)
    (AddChar.map_neg_eq_inv (ZMod.toCircle (N := n)) x).symm

private theorem sum_stdAddChar_mul_cyclicBasis
    (d : Type u) [Fintype d] [Nonempty d]
    (t : ZMod (Fintype.card d)) :
    (∑ x : d, ZMod.stdAddChar (t * cyclicBasisEquiv d x)) =
      if t = 0 then (Fintype.card d : ℂ) else 0 := by
  calc
    (∑ x : d, ZMod.stdAddChar (t * cyclicBasisEquiv d x)) =
        ∑ z : ZMod (Fintype.card d), ZMod.stdAddChar (t * z) := by
          refine Fintype.sum_equiv (cyclicBasisEquiv d) _ _ ?_
          intro x
          rfl
    _ = if t = 0 then (Fintype.card d : ℂ) else 0 := by
      split_ifs with ht
      · subst t
        simp
      · exact AddChar.sum_eq_zero_of_ne_one
          (ZMod.isPrimitive_stdAddChar (Fintype.card d) ht)

theorem teleportationPhase_conjTranspose_mul_self
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] (j : d) :
    Matrix.conjTranspose (teleportationPhase d j) * teleportationPhase d j = 1 := by
  rw [teleportationPhase, Matrix.diagonal_conjTranspose,
    Matrix.diagonal_mul_diagonal]
  ext x y
  by_cases hxy : x = y
  · subst y
    simpa only [Matrix.diagonal_apply_eq, Matrix.one_apply, if_pos] using
      star_stdAddChar_mul_self
        (cyclicBasisEquiv d j * cyclicBasisEquiv d x)
  · simp [hxy]

theorem teleportationShift_conjTranspose_mul_self
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] (i : d) :
    Matrix.conjTranspose (teleportationShift d i) * teleportationShift d i = 1 := by
  rw [teleportationShift, Matrix.conjTranspose_permMatrix]
  rw [← Matrix.permMatrix_mul]
  simp

theorem teleportationWeyl_conjTranspose_mul_self
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) :
    Matrix.conjTranspose (teleportationWeyl d outcome) *
        teleportationWeyl d outcome = 1 := by
  rw [teleportationWeyl, Matrix.conjTranspose_mul]
  calc
    Matrix.conjTranspose (teleportationShift d outcome.1) *
          Matrix.conjTranspose (teleportationPhase d outcome.2) *
          (teleportationPhase d outcome.2 * teleportationShift d outcome.1) =
        Matrix.conjTranspose (teleportationShift d outcome.1) *
          ((Matrix.conjTranspose (teleportationPhase d outcome.2) *
            teleportationPhase d outcome.2) * teleportationShift d outcome.1) := by
              simp only [Matrix.mul_assoc]
    _ = Matrix.conjTranspose (teleportationShift d outcome.1) *
          teleportationShift d outcome.1 := by
            rw [teleportationPhase_conjTranspose_mul_self]
            simp
    _ = 1 := teleportationShift_conjTranspose_mul_self d outcome.1

theorem teleportationWeyl_mul_conjTranspose_self
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) :
    teleportationWeyl d outcome *
        Matrix.conjTranspose (teleportationWeyl d outcome) = 1 := by
  rw [← Matrix.star_eq_conjTranspose, ← Matrix.mem_unitaryGroup_iff]
  rw [Matrix.mem_unitaryGroup_iff']
  simpa [Matrix.star_eq_conjTranspose] using
    teleportationWeyl_conjTranspose_mul_self d outcome

theorem teleportationWeyl_apply
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) (x y : d) :
    teleportationWeyl d outcome x y =
      ZMod.stdAddChar
          (cyclicBasisEquiv d outcome.2 * cyclicBasisEquiv d x) *
        if x = teleportationShiftPerm d outcome.1 y then 1 else 0 := by
  rw [teleportationWeyl, teleportationPhase, Matrix.diagonal_mul]
  simp only [teleportationShift, Equiv.Perm.permMatrix, PEquiv.toMatrix_apply,
    Equiv.toPEquiv_apply, Equiv.Perm.inv_def, Option.mem_def, Option.some.injEq]
  by_cases h : x = teleportationShiftPerm d outcome.1 y
  · rw [if_pos h, if_pos]
    exact (teleportationShiftPerm d outcome.1).symm_apply_eq.mpr h
  · rw [if_neg h, if_neg]
    intro hy
    exact h ((teleportationShiftPerm d outcome.1).symm_apply_eq.mp hy)

/-- The Weyl operator bundled as a reference isometry. -/
def teleportationWeylIsometry
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) : ReferenceIsometry d d where
  matrix := teleportationWeyl d outcome
  isometry := teleportationWeyl_conjTranspose_mul_self d outcome

/-- Generalized Bell vector `(U^(i,j) tensor I)|Phi>` for outcome `(i,j)`. -/
def generalizedBellPureVector
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) : PureVector (Prod d d) where
  amp x :=
    if cyclicBasisEquiv d x.1 =
        cyclicBasisEquiv d x.2 + cyclicBasisEquiv d outcome.1 then
      ((Real.sqrt (Fintype.card d : ℝ) : ℂ)⁻¹) *
        ZMod.stdAddChar
          (cyclicBasisEquiv d outcome.2 * cyclicBasisEquiv d x.1)
    else 0
  trace_rankOne_eq_one := by
    rw [rankOneMatrix_trace, dotProduct, Fintype.sum_prod_type]
    let c : ℂ := (Real.sqrt (Fintype.card d : ℝ) : ℂ)⁻¹
    let e := cyclicBasisEquiv d
    have hcard_pos : 0 < (Fintype.card d : ℝ) := by
      exact_mod_cast fintype_card_pos d
    have hsqrt_ne : Real.sqrt (Fintype.card d : ℝ) ≠ 0 :=
      ne_of_gt (Real.sqrt_pos.2 hcard_pos)
    have hsqrtC_ne : (Real.sqrt (Fintype.card d : ℝ) : ℂ) ≠ 0 := by
      exact_mod_cast hsqrt_ne
    calc
      (∑ x : d, ∑ y : d,
          (if e x = e y + e outcome.1 then
              c * ZMod.stdAddChar (e outcome.2 * e x) else 0) *
            star (if e x = e y + e outcome.1 then
              c * ZMod.stdAddChar (e outcome.2 * e x) else 0)) =
          ∑ x : d, c * c := by
            apply Finset.sum_congr rfl
            intro x _
            let y0 : d := e.symm (e x - e outcome.1)
            rw [Finset.sum_eq_single y0]
            · have hxy : e x = e y0 + e outcome.1 := by
                simp [y0, e]
              rw [if_pos hxy]
              have hcstar : star c = c := by simp [c]
              rw [star_mul, hcstar]
              calc
                (c * ZMod.stdAddChar (e outcome.2 * e x)) *
                    (star (ZMod.stdAddChar (e outcome.2 * e x)) * c) =
                    (c * c) *
                      (ZMod.stdAddChar (e outcome.2 * e x) *
                        star (ZMod.stdAddChar (e outcome.2 * e x))) := by ring
                _ = c * c := by rw [stdAddChar_mul_star_self, mul_one]
            · intro y _ hy
              have hne : e x ≠ e y + e outcome.1 := by
                intro hxy
                apply hy
                apply e.injective
                simpa [y0] using congrArg (fun z => z - e outcome.1) hxy.symm
              simp [hne]
            · simp
      _ = (Fintype.card d : ℂ) * (c * c) := by simp
      _ = 1 := by
        dsimp [c]
        field_simp [hsqrtC_ne]
        rw [← Complex.ofReal_natCast, ← Complex.ofReal_pow]
        exact congrArg Complex.ofReal (Real.sq_sqrt hcard_pos.le).symm

theorem generalizedBellPureVector_amp
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) (x : Prod d d) :
    (generalizedBellPureVector d outcome).amp x =
      if cyclicBasisEquiv d x.1 =
          cyclicBasisEquiv d x.2 + cyclicBasisEquiv d outcome.1 then
        ((Real.sqrt (Fintype.card d : ℝ) : ℂ)⁻¹) *
          ZMod.stdAddChar
            (cyclicBasisEquiv d outcome.2 * cyclicBasisEquiv d x.1)
      else 0 := by
  rfl

theorem generalizedBellPureVector_inner
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome other : Prod d d) :
    (∑ x : Prod d d,
      star ((generalizedBellPureVector d outcome).amp x) *
        (generalizedBellPureVector d other).amp x) =
      if outcome = other then 1 else 0 := by
  by_cases hout : outcome = other
  · subst other
    rw [if_pos rfl]
    simpa [rankOneMatrix_trace, dotProduct, mul_comm] using
      (generalizedBellPureVector d outcome).trace_rankOne_eq_one
  · rw [if_neg hout]
    rcases outcome with ⟨i, j⟩
    rcases other with ⟨i', j'⟩
    simp only [Prod.mk.injEq] at hout
    by_cases hi : i = i'
    · subst i'
      have hj : j ≠ j' := fun hj => hout ⟨rfl, hj⟩
      let e := cyclicBasisEquiv d
      let c : ℂ := (Real.sqrt (Fintype.card d : ℝ) : ℂ)⁻¹
      let t : ZMod (Fintype.card d) := e j' - e j
      have ht : t ≠ 0 := by
        intro ht0
        apply hj
        apply e.injective
        dsimp [t] at ht0
        exact (sub_eq_zero.mp ht0).symm
      rw [Fintype.sum_prod_type]
      calc
        (∑ x : d, ∑ y : d,
            star ((generalizedBellPureVector d (i, j)).amp (x, y)) *
              (generalizedBellPureVector d (i, j')).amp (x, y)) =
            c * c * ∑ x : d, ZMod.stdAddChar (t * e x) := by
              rw [Finset.mul_sum]
              apply Finset.sum_congr rfl
              intro x _
              let y0 : d := e.symm (e x - e i)
              rw [Finset.sum_eq_single y0]
              · have hxy : e x = e y0 + e i := by simp [y0, e]
                rw [generalizedBellPureVector_amp,
                  generalizedBellPureVector_amp, if_pos hxy, if_pos hxy]
                have hcstar : star c = c := by simp [c]
                calc
                  star (c * ZMod.stdAddChar (e j * e x)) *
                      (c * ZMod.stdAddChar (e j' * e x)) =
                      c * c *
                        (ZMod.stdAddChar (-((e j) * e x)) *
                          ZMod.stdAddChar (e j' * e x)) := by
                            rw [star_mul, hcstar, star_stdAddChar_eq_neg]
                            ring
                  _ = c * c *
                      ZMod.stdAddChar (-((e j) * e x) + e j' * e x) := by
                        rw [AddChar.map_add_eq_mul]
                  _ = c * c * ZMod.stdAddChar (t * e x) := by
                        congr 2
                        dsimp [t]
                        ring
              · intro y _ hy
                have hne : e x ≠ e y + e i := by
                  intro hxy
                  apply hy
                  apply e.injective
                  simpa [y0] using congrArg (fun z => z - e i) hxy.symm
                rw [generalizedBellPureVector_amp, if_neg hne]
                simp
              · simp
        _ = 0 := by
          rw [sum_stdAddChar_mul_cyclicBasis d t, if_neg ht, mul_zero]
    · rw [Fintype.sum_prod_type]
      apply Finset.sum_eq_zero
      intro x _
      apply Finset.sum_eq_zero
      intro y _
      by_cases hxy : cyclicBasisEquiv d x =
          cyclicBasisEquiv d y + cyclicBasisEquiv d i
      · have hxy' : cyclicBasisEquiv d x ≠
            cyclicBasisEquiv d y + cyclicBasisEquiv d i' := by
          intro h'
          apply hi
          apply (cyclicBasisEquiv d).injective
          have := hxy.symm.trans h'
          exact add_left_cancel this
        rw [generalizedBellPureVector_amp, generalizedBellPureVector_amp,
          if_pos hxy, if_neg hxy']
        simp
      · rw [generalizedBellPureVector_amp, if_neg hxy]
        simp

/-- Matrix whose columns are the generalized Bell vectors. -/
def generalizedBellBasisMatrix
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] :
    Matrix (Prod d d) (Prod d d) ℂ :=
  fun physical outcome => (generalizedBellPureVector d outcome).amp physical

theorem generalizedBellBasisMatrix_conjTranspose_mul_self
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] :
    Matrix.conjTranspose (generalizedBellBasisMatrix d) *
        generalizedBellBasisMatrix d = 1 := by
  ext outcome other
  rw [Matrix.mul_apply]
  simpa [generalizedBellBasisMatrix, Matrix.conjTranspose, Matrix.one_apply] using
    generalizedBellPureVector_inner d outcome other

theorem generalizedBellBasisMatrix_mul_conjTranspose_self
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] :
    generalizedBellBasisMatrix d *
        Matrix.conjTranspose (generalizedBellBasisMatrix d) = 1 := by
  rw [← Matrix.star_eq_conjTranspose, ← Matrix.mem_unitaryGroup_iff]
  rw [Matrix.mem_unitaryGroup_iff']
  simpa [Matrix.star_eq_conjTranspose] using
    generalizedBellBasisMatrix_conjTranspose_mul_self d

/-- Alice's projective generalized Bell measurement. -/
def generalizedBellPOVM
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] :
    POVM (Prod d d) (Prod d d) where
  effects outcome := rankOneMatrix (generalizedBellPureVector d outcome).amp
  pos outcome := rankOneMatrix_pos _
  sum_eq_one := by
    calc
      (∑ outcome : Prod d d,
          rankOneMatrix (generalizedBellPureVector d outcome).amp) =
          generalizedBellBasisMatrix d *
            Matrix.conjTranspose (generalizedBellBasisMatrix d) := by
              ext x y
              simp only [Matrix.sum_apply, rankOneMatrix_apply,
                generalizedBellBasisMatrix, Matrix.mul_apply,
                Matrix.conjTranspose_apply]
      _ = 1 := generalizedBellBasisMatrix_mul_conjTranspose_self d

private theorem inv_sqrt_mul_self_eq_card_inv
    (d : Type u) [Fintype d] [Nonempty d] :
    ((Real.sqrt (Fintype.card d : ℝ) : ℂ)⁻¹) *
        ((Real.sqrt (Fintype.card d : ℝ) : ℂ)⁻¹) =
      (Fintype.card d : ℂ)⁻¹ := by
  have hcard_pos : 0 < (Fintype.card d : ℝ) := by
    exact_mod_cast fintype_card_pos d
  have hsqrt_ne : Real.sqrt (Fintype.card d : ℝ) ≠ 0 :=
    ne_of_gt (Real.sqrt_pos.2 hcard_pos)
  have hsqrtC_ne : (Real.sqrt (Fintype.card d : ℝ) : ℂ) ≠ 0 := by
    exact_mod_cast hsqrt_ne
  field_simp [hsqrtC_ne]
  rw [← Complex.ofReal_natCast, ← Complex.ofReal_pow]
  exact congrArg Complex.ofReal (Real.sq_sqrt hcard_pos.le).symm

/-- One maximally entangled pair consumed by qudit teleportation.  Its pairing
fixes the two rank-`d` local registers, and its state is derived rather than
stored as an unconstrained field. -/
structure TeleportationEntanglementResource
    (d : Type u) [Fintype d] [DecidableEq d] where
  pairing : d ≃ d

namespace TeleportationEntanglementResource

/-- The actual pure state supplied by a maximally entangled resource pair. -/
def state
    {d : Type u} [Fintype d] [DecidableEq d] [Nonempty d]
    (resource : TeleportationEntanglementResource d) : PureVector (Prod d d) :=
  maximallyEntangledPureVector resource.pairing

/-- Schmidt rank represented by the paired local registers. -/
def rank
    {d : Type u} [Fintype d] [DecidableEq d]
    (_resource : TeleportationEntanglementResource d) : Nat :=
  Fintype.card d

/-- Entanglement cost, in ebits, of one maximally entangled pair. -/
def entanglementCost
    {d : Type u} [Fintype d] [DecidableEq d]
    (resource : TeleportationEntanglementResource d) : Real :=
  log2 resource.rank

end TeleportationEntanglementResource

/-- The rank-`d` shared pair actually consumed by the teleportation branch
calculation. -/
def teleportationEntanglementResource
    (d : Type u) [Fintype d] [DecidableEq d] :
    TeleportationEntanglementResource d where
  pairing := Equiv.refl d

/-- Effective uncorrected branch obtained by contracting Alice's Bell bra
with her half of the shared maximally entangled pair. -/
def bellContractionKraus
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) : CMatrix d :=
  fun bob input =>
    ∑ alice : d,
      star ((generalizedBellPureVector d outcome).amp (input, alice)) *
        (teleportationEntanglementResource d).state.amp (alice, bob)

theorem teleportationEntanglementResource_state
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] :
    (teleportationEntanglementResource d).state =
      maximallyEntangledPureVector (Equiv.refl d) := by
  rfl

theorem bellContractionKraus_uses_entanglementResource
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) :
    bellContractionKraus d outcome = fun bob input =>
      ∑ alice : d,
        star ((generalizedBellPureVector d outcome).amp (input, alice)) *
          (teleportationEntanglementResource d).state.amp (alice, bob) := by
  rfl

theorem bellContractionKraus_eq_card_inv_smul_conjTranspose_weyl
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) :
    bellContractionKraus d outcome =
      (Fintype.card d : ℂ)⁻¹ •
        Matrix.conjTranspose (teleportationWeyl d outcome) := by
  ext bob input
  rw [bellContractionKraus]
  simp only [Matrix.smul_apply, Matrix.conjTranspose_apply]
  rw [Finset.sum_eq_single bob]
  · simp only [TeleportationEntanglementResource.state,
      teleportationEntanglementResource, maximallyEntangledPureVector]
    simp only [Equiv.refl_apply, if_true]
    rw [generalizedBellPureVector_amp, teleportationWeyl_apply]
    have hsupport :
        cyclicBasisEquiv d input =
            cyclicBasisEquiv d bob + cyclicBasisEquiv d outcome.1 ↔
          input = teleportationShiftPerm d outcome.1 bob := by
      constructor
      · intro h
        apply (cyclicBasisEquiv d).injective
        simpa [teleportationShiftPerm] using h
      · intro h
        simpa [teleportationShiftPerm] using
          congrArg (cyclicBasisEquiv d) h
    by_cases h : cyclicBasisEquiv d input =
        cyclicBasisEquiv d bob + cyclicBasisEquiv d outcome.1
    · rw [if_pos h, if_pos (hsupport.mp h)]
      simp only [mul_one, star_mul, smul_eq_mul]
      have hcstar :
          star ((Real.sqrt (Fintype.card d : ℝ) : ℂ)⁻¹) =
            ((Real.sqrt (Fintype.card d : ℝ) : ℂ)⁻¹) := by simp
      rw [hcstar]
      calc
        star (ZMod.stdAddChar
            (cyclicBasisEquiv d outcome.2 * cyclicBasisEquiv d input)) *
              (Real.sqrt (Fintype.card d : ℝ) : ℂ)⁻¹ *
              (Real.sqrt (Fintype.card d : ℝ) : ℂ)⁻¹ =
            ((Real.sqrt (Fintype.card d : ℝ) : ℂ)⁻¹ *
              (Real.sqrt (Fintype.card d : ℝ) : ℂ)⁻¹) *
              star (ZMod.stdAddChar
                (cyclicBasisEquiv d outcome.2 * cyclicBasisEquiv d input)) := by ring
        _ = (Fintype.card d : ℂ)⁻¹ *
              star (ZMod.stdAddChar
                (cyclicBasisEquiv d outcome.2 * cyclicBasisEquiv d input)) := by
              rw [inv_sqrt_mul_self_eq_card_inv d]
    · rw [if_neg h, if_neg]
      · simp
      · exact fun h' => h (hsupport.mpr h')
  · intro alice _ halice
    simp [TeleportationEntanglementResource.state,
      teleportationEntanglementResource, maximallyEntangledPureVector, halice]
  · simp

theorem bellContractionKraus_conjTranspose_mul_self
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) :
    Matrix.conjTranspose (bellContractionKraus d outcome) *
        bellContractionKraus d outcome =
      ((Fintype.card d : ℂ)⁻¹ * (Fintype.card d : ℂ)⁻¹) •
        (1 : CMatrix d) := by
  rw [bellContractionKraus_eq_card_inv_smul_conjTranspose_weyl,
    Matrix.conjTranspose_smul]
  have hstar : star (Fintype.card d : ℂ)⁻¹ = (Fintype.card d : ℂ)⁻¹ := by simp
  rw [hstar, Matrix.smul_mul, Matrix.mul_smul,
    Matrix.conjTranspose_conjTranspose,
    teleportationWeyl_mul_conjTranspose_self, smul_smul]

theorem bellContractionKraus_krausAdjoint_one
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] :
    MatrixMap.krausAdjoint (bellContractionKraus d)
        (1 : CMatrix d) = 1 := by
  rw [MatrixMap.krausAdjoint]
  simp only [Matrix.mul_one]
  simp_rw [bellContractionKraus_conjTranspose_mul_self]
  ext x y
  have hcard : (Fintype.card d : ℂ) ≠ 0 := by
    exact_mod_cast Nat.ne_of_gt (fintype_card_pos d)
  simp [Matrix.sum_apply, Matrix.one_apply, Fintype.card_prod]
  by_cases hxy : x = y
  · subst y
    field_simp [hcard]
  · simp [hxy]

/-- The physical channel obtained after Alice's Bell measurement when Bob
forgets the outcome and applies no correction. -/
def uncorrectedTeleportationChannel
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] : Channel d d where
  map := MatrixMap.ofKraus (bellContractionKraus d)
  completelyPositive := MatrixMap.ofKraus_completelyPositive _
  tracePreserving :=
    MatrixMap.ofKraus_isTracePreserving_of_krausAdjoint_one _
      (bellContractionKraus_krausAdjoint_one d)
  mapsPositive := MatrixMap.ofKraus_mapsPositive _

theorem uncorrectedTeleportationChannel_offDiagonal
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (x y : d) (hxy : x ≠ y) :
    (uncorrectedTeleportationChannel d).map
        (Matrix.single x y (1 : Complex)) x y = 0 := by
  change (MatrixMap.ofKraus (bellContractionKraus d)
    (Matrix.single x y (1 : Complex))) x y = 0
  simp only [MatrixMap.ofKraus, LinearMap.coe_mk, AddHom.coe_mk, Matrix.sum_apply]
  simp_rw [bellContractionKraus_eq_card_inv_smul_conjTranspose_weyl]
  have hstar : star ((Fintype.card d : Complex)⁻¹) =
      (Fintype.card d : Complex)⁻¹ := by simp
  simp only [Matrix.conjTranspose_smul, hstar,
    Matrix.conjTranspose_conjTranspose, Matrix.smul_mul, Matrix.mul_smul,
    Matrix.smul_apply]
  rw [Fintype.sum_prod_type]
  simp only [Matrix.mul_apply, Matrix.conjTranspose_apply, Matrix.single,
    teleportationWeyl_apply]
  simp only [ite_and]
  simp
  apply Finset.sum_eq_zero
  intro i _
  by_cases hy : y = teleportationShiftPerm d i y
  · rw [if_pos hy]
    have hi0 : cyclicBasisEquiv d i = 0 := by
      have h : cyclicBasisEquiv d y =
          cyclicBasisEquiv d y + cyclicBasisEquiv d i := by
        simpa [teleportationShiftPerm] using congrArg (cyclicBasisEquiv d) hy
      have h' : cyclicBasisEquiv d y + cyclicBasisEquiv d i =
          cyclicBasisEquiv d y + 0 := by
        exact h.symm.trans (add_zero _).symm
      exact add_left_cancel h'
    have hx : x = teleportationShiftPerm d i x := by
      apply (cyclicBasisEquiv d).injective
      simp [teleportationShiftPerm, hi0]
    rw [← hy]
    simp only [if_pos hx]
    have ht : cyclicBasisEquiv d y - cyclicBasisEquiv d x ≠ 0 := by
      intro ht0
      apply hxy
      apply (cyclicBasisEquiv d).injective
      exact (sub_eq_zero.mp ht0).symm
    have hchar (j : d) :
        (starRingEnd Complex) (ZMod.stdAddChar
            (cyclicBasisEquiv d j * cyclicBasisEquiv d x)) *
          ZMod.stdAddChar
            (cyclicBasisEquiv d j * cyclicBasisEquiv d y) =
          ZMod.stdAddChar
            ((cyclicBasisEquiv d y - cyclicBasisEquiv d x) *
              cyclicBasisEquiv d j) := by
      change star (ZMod.stdAddChar
          (cyclicBasisEquiv d j * cyclicBasisEquiv d x)) *
        ZMod.stdAddChar
          (cyclicBasisEquiv d j * cyclicBasisEquiv d y) = _
      rw [star_stdAddChar_eq_neg, ← AddChar.map_add_eq_mul]
      congr 1
      ring
    simp_rw [hchar]
    rw [← Finset.mul_sum]
    rw [← Finset.mul_sum]
    rw [sum_stdAddChar_mul_cyclicBasis, if_neg ht]
    simp
  · rw [if_neg hy]

/-- Without Bob's outcome-conditioned correction, the Bell-measurement channel
is not the identity in every nontrivial finite dimension. -/
theorem uncorrectedTeleportationChannel_ne_idChannel
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (hcard : 1 < Fintype.card d) :
    uncorrectedTeleportationChannel d ≠ Channel.idChannel d := by
  let x : d := Classical.choice inferInstance
  obtain ⟨y, hyx⟩ := Fintype.exists_ne_of_one_lt_card hcard x
  have hxy : x ≠ y := Ne.symm hyx
  intro hchannel
  have hmap := congrArg Channel.map hchannel
  have hentry := congrArg
    (fun Phi : MatrixMap d d => Phi (Matrix.single x y (1 : Complex)) x y) hmap
  change (uncorrectedTeleportationChannel d).map
      (Matrix.single x y (1 : Complex)) x y =
    (Channel.idChannel d).map (Matrix.single x y (1 : Complex)) x y at hentry
  rw [uncorrectedTeleportationChannel_offDiagonal d x y hxy] at hentry
  simp [Channel.idChannel, MatrixMap.ofKraus, Matrix.single] at hentry

/-- Bob's outcome-conditioned Weyl correction channel. -/
def teleportationCorrection
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) : Channel d d where
  map := MatrixMap.ofKraus (fun _ : Unit => teleportationWeyl d outcome)
  completelyPositive := MatrixMap.ofKraus_completelyPositive _
  tracePreserving := by
    apply MatrixMap.ofKraus_isTracePreserving_of_krausAdjoint_one
    simp [MatrixMap.krausAdjoint, teleportationWeyl_conjTranspose_mul_self]
  mapsPositive := MatrixMap.ofKraus_mapsPositive _

/-- Corrected branch Kraus operator: Bob applies the Weyl correction after
Alice's Bell outcome. -/
def correctedTeleportationKraus
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) : CMatrix d :=
  teleportationWeyl d outcome * bellContractionKraus d outcome

theorem correctedTeleportationKraus_eq_card_inv_smul_one
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (outcome : Prod d d) :
    correctedTeleportationKraus d outcome =
      (Fintype.card d : ℂ)⁻¹ • (1 : CMatrix d) := by
  rw [correctedTeleportationKraus,
    bellContractionKraus_eq_card_inv_smul_conjTranspose_weyl,
    Matrix.mul_smul, teleportationWeyl_mul_conjTranspose_self]

theorem correctedTeleportationMap_eq_idChannel_map
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] :
    MatrixMap.ofKraus (correctedTeleportationKraus d) =
      (Channel.idChannel d).map := by
  apply LinearMap.ext
  intro X
  ext x y
  simp only [MatrixMap.ofKraus, LinearMap.coe_mk, AddHom.coe_mk,
    Matrix.sum_apply]
  simp_rw [correctedTeleportationKraus_eq_card_inv_smul_one]
  have hcard : (Fintype.card d : ℂ) ≠ 0 := by
    exact_mod_cast Nat.ne_of_gt (fintype_card_pos d)
  simp [Channel.idChannel, MatrixMap.ofKraus, Matrix.mul_apply,
    Matrix.one_apply, Fintype.card_prod]
  field_simp [hcard]

/-- The channel computed by all corrected teleportation branches. -/
def teleportationChannel
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] : Channel d d where
  map := MatrixMap.ofKraus (correctedTeleportationKraus d)
  completelyPositive := MatrixMap.ofKraus_completelyPositive _
  tracePreserving := by
    rw [correctedTeleportationMap_eq_idChannel_map]
    exact (Channel.idChannel d).tracePreserving
  mapsPositive := MatrixMap.ofKraus_mapsPositive _

private theorem channel_eq_of_map_eq
    {a : Type u} [Fintype a] [DecidableEq a]
    {b : Type v} [Fintype b] [DecidableEq b]
    {Phi Psi : Channel a b} (h : Phi.map = Psi.map) : Phi = Psi := by
  cases Phi with
  | mk phi phiCP phiTP phiPos =>
      cases Psi with
      | mk psi psiCP psiTP psiPos =>
          dsimp only at h
          cases h
          rfl

/-- The Bell-measurement and correction calculation implements the identity channel. -/
theorem teleportationChannel_eq_idChannel
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] :
    teleportationChannel d = Channel.idChannel d := by
  apply channel_eq_of_map_eq
  exact correctedTeleportationMap_eq_idChannel_map d

private theorem idChannel_prod_idChannel_applyState
    (d : Type u) [Fintype d] [DecidableEq d]
    (r : Type v) [Fintype r] [DecidableEq r]
    (rho : State (Prod r d)) :
    ((Channel.idChannel r).prod (Channel.idChannel d)).applyState rho = rho := by
  apply State.ext
  change MatrixMap.kron (Channel.idChannel r).map (Channel.idChannel d).map rho.matrix =
    rho.matrix
  ext x y
  simp [Channel.idChannel, MatrixMap.ofKraus, MatrixMap.kron, Matrix.single, ite_and]

/-- Teleportation preserves every joint state with an inaccessible reference system. -/
theorem teleportation_preserves_reference
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d]
    (r : Type v) [Fintype r] [DecidableEq r]
    (rho : State (Prod r d)) :
    ((Channel.idChannel r).prod (teleportationChannel d)).applyState rho = rho := by
  rw [teleportationChannel_eq_idChannel]
  exact idChannel_prod_idChannel_applyState d r rho

/-- Alice's generalized Bell measurement has two `d`-valued classical outcomes. -/
abbrev TeleportationOutcome (d : Type u) := Prod d d

theorem teleportationOutcome_card
    (d : Type u) [Fintype d] :
    Fintype.card (TeleportationOutcome d) = Fintype.card d ^ 2 := by
  simp [TeleportationOutcome, Fintype.card_prod, pow_two]

/-- The rank-`d` maximally entangled resource costs `log2 d` ebits. -/
def teleportationEntanglementCost
    (d : Type u) [Fintype d] [DecidableEq d] : Real :=
  (teleportationEntanglementResource d).entanglementCost

/-- The Bell outcome costs the logarithm of its `d^2`-element alphabet. -/
def teleportationClassicalCommunication
    (d : Type u) [Fintype d] : Real :=
  log2 (Fintype.card (TeleportationOutcome d) : Real)

theorem teleportationClassicalCommunication_eq_two_log2
    (d : Type u) [Fintype d] [Nonempty d] :
    teleportationClassicalCommunication d =
      2 * log2 (Fintype.card d : Real) := by
  rw [teleportationClassicalCommunication, teleportationOutcome_card]
  rw [Nat.cast_pow]
  have hcard : (Fintype.card d : Real) ≠ 0 := by
    exact_mod_cast Nat.ne_of_gt (fintype_card_pos d)
  unfold log2
  rw [pow_two, Real.log_mul hcard hcard]
  ring

/-- The protocol consumes one rank-`d` maximally entangled pair and transmits
one of `d^2` Bell outcomes, matching Wilde's qudit resource inequality. -/
theorem teleportation_resource_costs
    (d : Type u) [Fintype d] [DecidableEq d] [Nonempty d] :
    (teleportationEntanglementResource d).state =
        maximallyEntangledPureVector (Equiv.refl d) ∧
      (teleportationEntanglementResource d).rank = Fintype.card d ∧
      teleportationEntanglementCost d = log2 (Fintype.card d : Real) ∧
      teleportationClassicalCommunication d =
        2 * log2 (Fintype.card d : Real) := by
  exact ⟨teleportationEntanglementResource_state d, rfl, rfl,
    teleportationClassicalCommunication_eq_two_log2 d⟩

end

end QIT
